# Project information
site_name: 'bsutils'
site_description: 'Pacote para comunicação wifi e serial'
site_author: 'Gabriel Mauly'

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'orange'
  language: 'pt'

plugins:
    - search
    - pdf-export

markdown_extensions:
  - codehilite